exec-once=~/.config/mango/autostart.sh
# exec-once=foot --app-id=mpc.mpd -e rmpc
exec-once=qutebrowser
exec-once=$TERMINAL --app-id=home.foot -e tmux new -As home
exec-once=tmux new -Ads mail aerc
exec-once=mmsg dispatch view,3
