exec-once=~/.config/mango/autostart.sh
exec-once=$TERMINAL --app-id=mpc.mpd -e rmpc
exec-once=qutebrowser
exec-once=$TERMINAL --app-id=home.foot -e tmux new -As home
exec-once=tmux new -Ads mail 'while true; do; aerc; done'
exec-once=mmsg -d view,3
