source "$HOME/.config/shell/aliases/misc.sh"
source "$HOME/.config/shell/aliases/cargo.sh"
source "$HOME/.config/shell/aliases/ls.sh"
source "$HOME/.config/shell/aliases/git.sh"
source "$HOME/.config/shell/aliases/nvim.sh"
