[mgr]
# show_hidden = true
linemode = "size"

[opener]
zathura = [
	{ run = 'zathura "$@"', orphan = true, for = "unix" },
]
browser = [
	{ run = '$BROWSER "$@"', orphan = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = ["zathura", "browser", "edit"] },
]
