#!/bin/sh

. "$HOME/.config/river/variables"

# uk keyboard layout
riverctl keyboard-layout gb

# Set background and border color
riverctl background-color 0x101010
riverctl border-color-focused 0xe4a382 # ee
riverctl border-color-unfocused 0x6f6f70 # aa

# Set keyboard repeat rate
riverctl set-repeat 100 400

riverctl hide-cursor when-typing enabled
riverctl focus-follows-cursor always

# Rules
riverctl rule-add -title "music_controller.sh" tags "$(get_tag 1)"
riverctl rule-add -app-id "music" tags "$(get_tag 1)"
riverctl rule-add -app-id "zen" tags "$(get_tag 2)"
riverctl rule-add -title "general" tags "$(get_tag 3)"
riverctl rule-add -app-id "obsidian" tags "$(get_tag 4)"

riverctl rule-add -app-id "im.dino.Dino" tags "$(get_tag 7)"
riverctl rule-add -app-id "discord" tags "$(get_tag 8)"
riverctl rule-add -app-id "steam" tags "$(get_tag 9)"
riverctl rule-add -title "btop" tags "$(get_tag 10)"

riverctl rule-add -app-id "Pinentry-gtk" float
riverctl rule-add -app-id "mpv" float
riverctl rule-add -app-id "mpv" dimensions 1500 800
riverctl rule-add -app-id "vimiv" float

riverctl rule-add -app-id "com.popup.app" float
riverctl rule-add -app-id "com.popup.app" dimensions 1000 500

# server side border decorations
riverctl rule-add ssd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 &

riverctl default-attach-mode below

# screencast fix
# export XDG_CURRENT_DESKTOP=river
# systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
# systemctl --user restart xdg-desktop-portal
