#!/bin/sh

. "$HOME/.config/river/variables"

# uk keyboard layout
riverctl keyboard-layout gb

# cursor theme
riverctl xcursor-theme capitaine-cursors 31

# Set background and border color
riverctl background-color 0x101010
riverctl border-color-focused "$(cat "$HOME"/.config/river/colors)"
riverctl border-color-unfocused 0x6f6f7099

# Set keyboard repeat rate
riverctl set-repeat 100 400

riverctl hide-cursor when-typing enabled
riverctl focus-follows-cursor always
riverctl set-cursor-warp on-focus-change

# Rules
riverctl rule-add -app-id "mpc.mpd" tags "$(get_tag 1)"
riverctl rule-add -app-id "music" tags "$(get_tag 1)"
riverctl rule-add -app-id "zen" tags "$(get_tag 2)"
riverctl rule-add -app-id "org.qutebrowser.qutebrowser" tags "$(get_tag 2)"
riverctl rule-add -app-id "general" tags "$(get_tag 3)"
riverctl rule-add -app-id "obsidian" tags "$(get_tag 4)"

riverctl rule-add -app-id "im.dino.Dino" tags "$(get_tag 7)"
riverctl rule-add -app-id "discord" tags "$(get_tag 8)"
riverctl rule-add -app-id "steam" tags "$(get_tag 9)"
riverctl rule-add -app-id "Btop" tags "$(get_tag 10)"
riverctl rule-add -title "Btop" tags "$(get_tag 10)"

riverctl rule-add -app-id "Pinentry-gtk" float
riverctl rule-add -app-id "mpv" float
riverctl rule-add -app-id "vimiv" float

riverctl rule-add -app-id "com.popup.app" float
riverctl rule-add -app-id "com.popup.app" dimensions 1000 500

# server side border decorations
riverctl rule-add ssd

riverctl default-attach-mode below
