#!/bin/sh

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

"$HOME/.config/river/general"
"$HOME/.config/river/mappings"
"$HOME/.config/river/layout"
"$HOME/.config/river/startup"
