#!/bin/sh

#################
# RELOAD SCRIPT #
#################

. "$HOME/.config/river/variables"

killall waybar; spawn waybar
killall swww-daemon; spawn swww-daemon

spawn "$HOME/.config/river/general"
spawn "$HOME/.config/river/mappings"
