#!/bin/sh

#################
# RELOAD SCRIPT #
#################

. "$HOME/.config/river/variables"

killall waybar; spawn waybar
killall swww-daemon; spawn swww-daemon

[ -e "$HOME/.config/river/monitors" ] && "$HOME/.config/river/monitors"
"$HOME/.config/river/general"
"$HOME/.config/river/mappings"
"$HOME/.config/river/layout"
