#!/bin/sh

###########
# STARTUP #
###########

. "$HOME/.config/river/variables"

# daemons
spawn swww-daemon 
spawn waybar
spawn swaync
spawn mpd

# startup applications
spawn "$terminal --class=mpc --title=mpc -e ~/.scripts/tmux_rmpc"
spawn "$HOME/.scripts/browser_select"
spawn "$terminal --class=general --title=general -e tmux new -s general"

spawn "tmux new -ds mail 'while true; do; aerc; done'"

riverctl set-focused-tags "$(get_tag 3)"
