#!/bin/sh

#############
# VARIABLES #
#############

terminal=ghostty
terminal_launch="$terminal -e" # ghotty start
drun="zsh -ci fuzzel"
browser="zen-browser"

sigwb="$HOME"/.config/river/signal_waybar

get_tag() {
    tag=$((1 << ($1 - 1)))
    echo $tag
}

spawn() {
    riverctl spawn "$@"
}
