#!/bin/sh

path_appunti="$HOME/Documents/Appunti"

tmux rename-window "Index"
tmux new-window -n "Dump" -c "$path_appunti/"

tmux select-window -t 0
tmux select-window -t 1
tmux send-keys "vi -S Session.vim" Enter
