#!/bin/sh
. "$HOME/.scripts/variables"

spawn() {
    riverctl spawn "$1"
}

browser_list="qutebrowser zen-browser"

spawn "$(echo "$browser_list" | sed 's/ /\n/g' | $DMENU --placeholder="Select a startup Browser..." -l 3)"
