#!/bin/sh

notes_path="$HOME/Documents/Appunti/"
terminal="wezterm start" 

note="$notes_path$(find "$notes_path" | sed "s|$notes_path||g" | grep "_notebook.md" | exec wofi --show dmenu)"

if [ "$note" != "$notes_path" ]; then
    $terminal nvim "$note"
fi
