#!/bin/sh
. "$HOME/.scripts/variables"

exist() {
    command -v "$1" >/dev/null 2>&1
}

wallpapers_folder="$HOME/Pictures/wallpapers/"

if [ -f "$1" ]; then
    theme="$1"
else
    if [ -d "$1" ]; then
        wallpapers_folder="$1"
    fi
    if exist nsxiv; then
        theme="$(nsxiv -N "com.popup.app" -rotb $wallpapers_folder/*)"
    elif exist $DMENU; then
        theme="${wallpapers_folder}$(
            find "$wallpapers_folder" -type f -printf '%P\n' |
                grep --invert-match "^$" | $DMENU --placeholder="Select a theme..."

        )"
    fi
fi

if [ -f "$theme" ]; then
    awww img "$theme" &&
        exist wal && wal --cols16 lighten --backend colorthief -tnqei "$theme"
    ~/.scripts/pywal_update > /dev/null 2>&1
fi
