#!/bin/sh
. "$HOME/.scripts/variables"

wallpapers_folder="$HOME/.config/wallpapers/"

sh -c "swww img ${wallpapers_folder}$(find "$wallpapers_folder" -printf '%P\n' | grep --invert-match "^$" | $DMENU --placeholder="Select a wallpaper...")"
