#!/bin/sh
. "$HOME/.scripts/variables"

exist() {
    command -v "$1" >/dev/null 2>&1
}

wallpapers_folder="$HOME/.config/wallpapers/"
wallpaper="${wallpapers_folder}$(find "$wallpapers_folder" -printf '%P\n' | grep --invert-match "^$" | $DMENU --placeholder="Select a wallpaper...")"
if [ "$wallpaper" != "$wallpapers_folder" ]; then
    swww img "$wallpaper"
    exist wal && wal -stnqei $wallpaper
fi
